### ISSUE TITLE
Update metric mappings

### ISSUE THREAD

**Issue by SuperQ** [digitalocean/bind_exporter#12]
Going over the XML, we've found a couple of issues.

Server Stats:
`QryDuplicate` is listed as an "error", it's actually a separate statistic for incoming query duplicates.  It should be something like `bind_queries_duplicated_total`

`QryRecursion` seems to be missing from the stats.  How about `bind_query_recursions_total`.

**Comment by grobie** [comment]
@SuperQ The assumption was that `sum(bind_resolver_queries_total) == bind_query_recursions_total`. That's not the case though on our nodes. I'll add it.
