### ISSUE TITLE
Detail command flags or missing metrics?

### ISSUE THREAD

**Issue by hiscal2015** [digitalocean/bind_exporter#24]
Hi, 

I'm trying to use this grafana dashboard with bind_exporter:
https://grafana.com/dashboards/1666

bind_exporter started with below flags:
/usr/local/bin/bind_exporter -bind.pid-file /var/run/named/named.pid -bind.stats-groups "server,view,tasks"

But why I only can see below a few metrics items?
![bind](https://cloud.githubusercontent.com/assets/15604715/24385918/527c5bbc-139f-11e7-9231-3afcd8247179.jpg)

From the dashboard, seems there should be some other metrics we can use e.g. "bind_incoming_queries_total", "bind_incoming_requests_total", "bind_responses_total" ..etc..

**Comment by grobie** [comment]
What's in the logs? What's the value of bind_up?

**Comment by hiscal2015** [comment]
@grobie Thanks for the reminder, I found bind_up is 0, then checked logs and found connection refused at port 8053, I realized I defined with wrong port in statistics-channels:
```
statistics-channels {
  inet 127.0.0.1 port 8080 allow { 127.0.0.1; };
};
```

**Comment by grobie** [comment]
Alternatively, change the default of the -bind.stats-url flag. I just
realized that we use a different default of that flag than in the README
snippet. Feel free to send a PR to update the README.
