### ISSUE TITLE
Megacheck and go1.8.x

### ISSUE THREAD

**Issue by mjtrangoni** [digitalocean/bind_exporter#25]
Hi,
I wanted to report that some vendors are actually outdated and [megacheck](https://github.com/dominikh/go-tools/tree/master/cmd/megacheck) report some possible errors.
Are you thinking about doing a new release? TravisCI should use go1.8.x instead of 1.7.

See,
```
bind/v2/v2.go:108:9: should use type conversion instead of struct literal (S1016)
bind_exporter.go:476:28: prometheus.Handler is deprecated: Please note the issues described in the doc comment of InstrumentHandler. You might want to consider using promhttp.Handler instead (which is not instrumented).  (SA1019)
```

**Comment by grobie** [comment]
Except for the prometheus.Handler, the issues have been fixed. There isn't a great alternative available for the Handler right now, besides doing all the instrumentation manually.
