### ISSUE TITLE
Problem with go get github.com/neezgee/apache_exporter

### ISSUE THREAD

**Issue by petarkozic** [digitalocean/bind_exporter#33]
Centos 6.7
go version go1.8.3 linux/amd64

I installed several exporter without problems !

When type
go get github.com/neezgee/apache_exporter
nothing happend !!
Some help ?

**Comment by grobie** [comment]
Please don't open issues in unrelated repositories.

Please close @cagedmantis

**Comment by petarkozic** [comment]
OHHH, my mistake. Sorry !!!!
