### ISSUE TITLE
Bind process information missing on FreeBSD 11.1

### ISSUE THREAD

**Issue by arj22** [digitalocean/bind_exporter#41]
I have set the bind.pid-file to the right location but the exporter doesn't show any process metrics. The resolver and response metrics show up fine. I am mostly interested in the file descriptor info.

**Comment by grobie** [comment]
The process collector provided by the Prometheus golang client library only supports Linux at the moment.

https://github.com/prometheus/client_golang/blob/5b23715facdef1452016bae512489c3cdf82458c/prometheus/process_collector.go#L32-L33

Adding support for FreeBSD shouldn't be that hard.

**Comment by raybellis** [comment]
On FreeBSD you have to mount the `linprocfs` in `/proc`.
