### ISSUE TITLE
-bash: ./bind_exporter: cannot execute binary file

### ISSUE THREAD

**Issue by guaychou** [digitalocean/bind_exporter#51]
Hey sir , 
 when i want to run binary file version i get these error : 
-bash: ./bind_exporter: cannot execute binary file

Please help me , i dont know what to do, thanks

**Comment by woodliu** [comment]
@guaychou this may because the file is built in i386 ,while you are useing x86-64,you can build this by youself, that could be work

**Comment by guaychou** [comment]
@woodliu Hey sir , thanks for your advise , you are right . I already build it myself , and that's work. Thank you

**Comment by alexjfisher** [comment]
Looks like the binary release provided is actually built for MacOS.
